### PR TITLE
Exercise Cards and Schedule Pages with Night Mode

### LINKED ISSUE #178: [Bug]:  Incompatibility of Cards on Guide and Schedule Pages with Night Mode
### What happened?

Hi there! I hope you're doing well. I'd like to bring to your attention an incompatibility issue I've noticed with the night mode feature in your repository. While the night mode itself works great, there seems to be a problem with the display of cards on both the Guide and Schedule pages.

When the night mode is enabled, the cards on these pages appear to have insufficient contrast or inappropriate styling, making them difficult to read or distinguish from one another. This significantly hinders the overall user experience, especially for those who rely on the night mode for accessibility or personal preference reasons.

To resolve this issue, I suggest reviewing the styles applied to the cards on the Guide and Schedule pages when the night mode is active. Consider adjusting the text color, background color, or any other relevant styling properties to ensure better visibility and readability.

Thank you for your attention to this matter. I believe addressing this issue will greatly enhance the usability and accessibility of your repository. Please let me know if you need any additional information or if there's anything else I can do to assist you.

### Add screenshots

Screenshot 2023-06-07 174651

### What browsers are you seeing the problem on?

_No response_

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by manuel12**
These changes fixes #178

I updated Card.jsx and SchedulePage.jsx to change styling depending on themeName.

I also made the exercises and schedule names italic.

This is how it looks now on dark mode for exercise cards:

image

And this is how  it looks like now on dark mode for schedules:

image

### CODE REVIEW

**Review by gabrysia694 — CHANGES_REQUESTED** [review]
I noticed that some cards have excessive space between img and exercise description like so
obraz_2023-06-17_001406524
Do you think you could take a look at it and change a bit so it looks more like this?
xx

**Comment by manuel12** [comment]
@gabrysia694 Yes definitely, I will make an update :)

**Comment by manuel12** [comment]
@gabrysia694 Would it be ok like this?

image

**Review by gabrysia694 — APPROVED** [review]
Looks perfect now, thank you Manuel :)

**Pull request merged**
