### PR TITLE
Add hamburger menu

### LINKED ISSUE #211: [style]: Add a hamburger button and menu on mobile resolutions
### What's the style idea?

We could add a hamburger menu for mobile resolutions this way the current navbar elements would not appear all crammed together.

### Add screenshots

The navbar looks like this on mobile resolutions currently:

image

I could make it look something like this:

image

Please assign this to me if you agree with the changes :)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by manuel12**
@gabrysia694  This fixes #211.

I've updated the navbar's ul and navlink element styles to accomodate  for the new navbar.
I've added a hamburger button and added styles for it and the navbar on App.css.

The navbar looks like this on light mode when it's closed:

image

Like this when it's opened:

image

The navbar looks like this when closed on dark mode:

image

And like this when it's open on dark mode:

image

### CODE REVIEW

**Review by gabrysia694 — CHANGES_REQUESTED** [review]
I love that but wouldn't it be better if there was a hamburger button when the menu is closed and the X button once it's opened to let the user know it's the button that's closing the menu?

**Comment by manuel12** [comment]
> I love that but wouldn't it be better if there was a hamburger button when the menu is closed and the X button once it's opened to let the user know it's the button that's closing the menu?

You're totally right. I will make an update.

**Comment by manuel12** [comment]
Now it's like this when  navbar closed:

image

And like this when opened:

image

**Review by gabrysia694 — APPROVED** [review]
Looks good now, thank you!

**Pull request merged**
