### PR TITLE
Update Contributing_Guidelines.md

### PR DESCRIPTION
**Pull request by Aditya-Naresh**
updated the template to accommodate the exercise video feature. In the template the <a> tag was replaced by a hidden div accommodating i-frame which will play the video

### CODE REVIEW

**Review by Aditya-Naresh — COMMENTED** [review]
The changes are in the contributing guidelines with updated template, index.html for all the existing templates of exercises, style.css for the iframe  and a new script.js to switch between exercise card and the video

**Review by gabrysia694 — CHANGES_REQUESTED** [review]
Looks good but could you add margin-top to iframe so that the first row doesn't stick to the navbar after clicking? Pointer cursor after hovering on the card would be a nice addition too.

**Comment by Aditya-Naresh** [comment]
@gabrysia694 It's done

**Review by Aditya-Naresh — COMMENTED** [review]
As requested, added the CSS to show cursor as a pointer while hovering over the card and the button  and added margin on top for iframe

**Review by gabrysia694 — APPROVED** [review]

**Comment by gabrysia694** [comment]
> As requested, added the CSS to show cursor as a pointer while hovering over the card and the button and added margin on top for iframe

awesome, thank you!

**Pull request merged**
