### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by Vishal-Parasram**
Added Glute Bridge exercise

### CODE REVIEW

**Review by gabrysia694 — CHANGES_REQUESTED** [review]
Code looks good but please fix indentation.

**Comment by Vishal-Parasram** [comment]
Ok

**Review by gabrysia694 — APPROVED** [review]
Looks good, thank you!

**Comment by Vishal-Parasram** [comment]
Thanks for giving me chance to contribute

**Pull request merged**
