### PR TITLE
created Contribution_Guidelines.md

### PR DESCRIPTION
**Pull request by harisdev-netizen**
created Contribution_Guidelines.md kindly review it. Don't forget to add me to contributors team, I have just started contributing to open-source and it would mean a lot.  Thank you.

### CODE REVIEW

**Review by gabrysia694 — CHANGES_REQUESTED** [review]
Looks good but please move the instruction on how to fill the template from README.md to Contributing so it's all in one place.

**Comment by harisdev-netizen** [comment]
> Looks good but please move the instruction on how to fill the template from README.md to Contributing so it's all in one place.

Got it. On it.

**Review by gabrysia694 — APPROVED** [review]
Perfect! Thank you so much for contributing.

**Comment by harisdev-netizen** [comment]
> Perfect! Thank you so much for contributing.

Do ping me for future projects contribution. I would really love to contribute in future as well. Don't forget adding me to contributors list.

**Comment by gabrysia694** [comment]
> > Perfect! Thank you so much for contributing.
> 
> Do ping me for future projects contribution. I would really love to contribute in future as well. Don't forget adding me to contributors list.

I will, thank you! I have another beginner friendly respository called MyPetSpotlight if you wish to contribute :)

**Comment by harisdev-netizen** [comment]
> > > Perfect! Thank you so much for contributing.
> > 
> > 
> > Do ping me for future projects contribution. I would really love to contribute in future as well. Don't forget adding me to contributors list.
> 
> I will, thank you! I have another beginner friendly respository called MyPetSpotlight if you wish to contribute :)

Great. I'll head over to the new project of yours. Thank you

**Pull request merged**
