### PR TITLE
Scrollbar will appear when content overflows.

### PR DESCRIPTION
**Pull request by Antardas**
added scroll bar if the content is overflow
Issue: https://github.com/gabrysia694/Gym-Junkies/issues/114
Prev
image
Now
image

### CODE REVIEW

**Comment by priyankarpal** [comment]
@Antardas could you add a good title & clear description with before & after screenshots to understand the fixed issue? 

also, add the issue number.

**Comment by Antardas** [comment]
> @Antardas could you add a good title & clear description with before & after screenshots to understand the fixed issue?
> 
> also, add the issue number.

can you please check now? Actually, It's my first step to contributing open source project.

**Comment by priyankarpal** [comment]
> > @Antardas could you add a good title & clear description with before & after screenshots to understand the fixed issue?
> > also, add the issue number.
> 
> can you please check now? Actually, It's my first step to contributing open source project.

what if we remove all scrollbars and add a min-height & width?

**Comment by Antardas** [comment]
> > > @Antardas could you add a good title & clear description with before & after screenshots to understand the fixed issue?
> > > also, add the issue number.
> > 
> > 
> > can you please check now? Actually, It's my first step to contributing open source project.
> 
> what if we remove all scrollbars and add a min-height & width?

Yeah We can do it, but it will not look good if we have long and Short content mixed-up

**Review by priyankarpal — APPROVED** [review]

**Review by gabrysia694 — APPROVED** [review]

**Pull request merged**
